services:

  postgres:
    image: 'postgres:15.3'
    container_name: my-app-keycloak-postgres    
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
    ports:
      - "5434:5432"
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
      # - ./scripts/keycloak/init-database.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: "exit 0"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: my-app-keycloak
    command: 
      - start-dev
      - --import-realm
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: keycloak
        KC_DB_SCHEMA: public
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  keycloak-postgres-data:

networks:
  default:
    external: true
    name: development
